name: build-linux

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]

permissions:
  contents: write   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install OpenGL / X11 build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config \
            libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev \
            libxinerama-dev libx11-dev xorg-dev \
            libpcap-dev        

      - name: Build via Makefile
        env:
          GOOS:   linux
          GOARCH: amd64
        run: |
          make clean
          make all
          mkdir -p dist
          mv fynewire dist/fynewire-linux-amd64

      - uses: actions/upload-artifact@v4
        with:
          name: fynewire-linux-amd64
          path: dist/fynewire-linux-amd64

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          tag:  ${{ github.ref_name }}
          artifacts: "**/fynewire-linux-amd64"
          generateReleaseNotes: true
