name: build-linux

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install libpcap headers
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev     # needed for sniffer.c to compile

      - name: Build via Makefile
        env:
          GOOS:   linux
          GOARCH: amd64
        run: |
          make clean
          make all
          mkdir -p dist
          mv fynewire dist/fynewire-linux-amd64   # produced by `make all`

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fynewire-linux-amd64
          path: dist/fynewire-linux-amd64

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          tag:  ${{ github.ref_name }}
          artifacts: "**/fynewire-linux-amd64"
          generateReleaseNotes: true
